Disable minimize jar because it broke extensions
- Maven shade plugin's minimze jar option removed classes from the core that weren't used by the core itself, even though there are used by the extensions (the doors). As such, the plugin ran into NoClassDefFoundErrors during runtime. Disabling this option resolved the issue.