Fix dependencies for door types
- The door types didn't relocate dependencies, which was a problem for the types using Flogger, as loading them would result in a NoClassDefFoundError. This has been resolved by using the maven-shade-plugin to transform the classes to use the relocated locations of the dependencies. Only the classes in the doors package itself are included in the shaded artifact. This is done to ensure we don't shade any dependencies into the doortype jars.