Implemented shared ownership
- Implemented door ownership adding/removing commands.
- Added permission level requirements for different door attributes.
- Added "/BigDoors addowner {door} <player> [permission]" and "/BigDoors removeowner {door} <player>".
- Added waitForRemoveOwner and waitForAddOwner command waiters.
- Added "/BigDoors help" which displays the same stuff as "/BigDoors" for now.
- Added config option to make backup of database file before upgrades. (default = true).
- Upgraded database to v3. sqlUnion now has UNIQUE constraint on playerID,doorUID.
- Split up separate db upgrades into separate functions. Makes it a bit easier to keep track of everything.
- Applied some formatting to configOption (rewrite incoming, though).
- Removed noClassDefFoundError message logging for worldGuard and plotSquared compat hook loading. I know what the error is (incorrect version), no need to write to file.
- getDoor() no longer just takes a UID, but also a playerUUID, to obtain the version for the correct player (with correct permission). Can just pass a nullptr to get the door for any user (with forced low permission).
- Made en_US.txt read-only.
- Changed some lines in en_US.txt to make more sense.